Repository liqd/a4-meinberlin, pull requests merged in 2018-10, with the labels that each got.

#1611 Ka 2018 10 add location and topic to projects
  meinberlin/apps/projects/admin.py
  meinberlin/config/settings/base.py
  package.json
  requirements/base.txt
Labels: depending

#1624 Mn 2018 10 add vector tiles
  meinberlin/apps/budgeting/templates/meinberlin_budgeting/proposal_list.html
  meinberlin/apps/kiezkasse/templates/meinberlin_kiezkasse/proposal_list.html
  meinberlin/apps/mapideas/templates/meinberlin_mapideas/mapidea_detail.html
  meinberlin/apps/mapideas/templates/meinberlin_mapideas/mapidea_list.html
  meinberlin/apps/maps/assets/map_choose_polygon_with_preset.js
  meinberlin/apps/maps/templates/meinberlin_maps/map_choose_polygon_with_preset_widget.html
  meinberlin/apps/maps/widgets.py
  meinberlin/apps/maptopicprio/templates/meinberlin_maptopicprio/maptopic_detail.html
  meinberlin/apps/maptopicprio/templates/meinberlin_maptopicprio/maptopic_list.html
  meinberlin/apps/plans/assets/plans_map.jsx
  meinberlin/apps/plans/templates/meinberlin_plans/plan_detail.html
  meinberlin/apps/plans/templates/meinberlin_plans/plan_list.html
  meinberlin/config/settings/base.py
  meinberlin/templates/a4maps/map_choose_point_widget.html
  package.json
  requirements/base.txt
  webpack.common.js
Labels: depending, incomplete

#1631 adding css for newly added class names from adhocracy to change colou…
  meinberlin/assets/scss/components/_progress.scss
  package.json
  requirements/base.txt
Labels: depending

#1638 changing max height to max width
  meinberlin/templates/newsletter_base.html
Labels: help wanted
